version: "3.8"

services:

  db-dev:
    image: mysql:8.0
    expose: 
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'db4dev$'
      MYSQL_ROOT_PASSWORD: 'db4dev$'
    volumes:
      - db-dev-data:/var/lib/mysql
    
  api-dev:
    build: ./
    volumes:
      - ./:/app
    ports: 
      - "8081:5000"
    environment:
      DB_HOST: db-dev
      DB_USER: 'admin'
      DB_PASS: 'db4dev$'
      DB_PORT: '3306'
    depends_on:
      - db-dev
    command: ["python", "app.py"]
    restart: always

volumes:
  db-dev-data:
