version: "3.8"

services:
  
  db-test:
    image: mysql:8.0
    expose: 
      - "3306"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'db4test$'
      MYSQL_ROOT_PASSWORD: 'db4test$'
    volumes:
      - db-test-data:/var/lib/mysql

  api-test:
    build: ./
    volumes:
      - ./:/app
    ports: 
      - "8082:5000"
    environment:
      DB_HOST: db-test
      DB_USER: 'admin'
      DB_PASS: 'db4test$'
      DB_PORT: '3307'
    depends_on:
      - db-test
    command: ["python", "app.py"]
    restart: always

volumes:
  db-test-data:

